baseurl = "https://oli-blakey.github.io/dyslexiasupportteaching.co.uk/"
languageCode = "en-us"
title = "Dyslexia support teaching"
theme = "hugo-creative-theme"
googleAnalytics = ""

enableInlineShortcodes = true


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Daphne Blakey"
	description = "Dyslexia Support teacher"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Dyslexia support teaching"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			location = "Location"
			portfolio = "Portfolio"
			photos = "Photos"
			testimonials = "Testimonials"
			method    = "Method"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Unlocking your child's full potential"
		subtitle   = "After-school and weekend tuition using a structured multi-sensory literacy programme for pupils aged five and over, who may be experiencing some learing difficulties."
		buttonText = "Contact me"


	# About section
	[params.about]
		headline    = "I can help your child to reach their full potential at school"
		description = "I offer individual tuition for children from the age of 5 to help them overcome the challenges to learning and communication arising from dyslexia, Aspergers, dyspraxia and a wide variety of other complex difficulties.</br> Based on over 20 years of experience, my approach is to develop a personalised learning schedule for every learner which is tailored to their needs, and which is adapted in response to their progress. My aim is to work alongside families and school so that, together, we can establish the solid building blocks that will allow the learner to achieve in their learning and reach their full potential."
		descriptionShowMore ="I believe that perceptual skills are key to learning. I focus on developing these skills. A typical teaching strategy will begin with recognising the basic sound structure of words. We will then progress to sentence construction, building grammatical awareness, often making up ‘silly sentences’ from random words but in a set grammatical pattern. I make time to talk and have fun, thereby building confidence, and don’t move on until the learning associated with any one area is fully consolidated.</br> I have an excellent range of specialist teaching resources and equipment, many of which are multi-sensory to help enhance concentration, interest, enjoyment and memory skills.</br> Having first trained as a Montessori teacher, I then studied with the Hornsby International Dyslexia Centre and hold a number of teaching and assessment qualifications from Dyslexia Action. My most recent training has being the study of ‘Structured, Cumulative Multisensory Tuition for Learners with Dyslexia’. I work in a primary school where I have attended many county based training sessions."
		descriptionOld = "My name is Daphne Blakey, I am a qualified specialist dyslexia teacher with over twenty years of experience, currently working in a local primary school. I specialise in helping young children with learning and commication difficulties."
		buttonText  = "Contact details"

	# Gallery
	[params.gallery]
		image1 = "img/header.jpg"

	[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

    # Testimonials
	[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

    # Fees
    [params.fees]
    enable = true
    title = "Fees"
	fees = "1hr £24, Traveling costs 45p per a mile"
	cancellationPolicy = "24 hours notice required, otherwise a 50% charge  will be applied"

	# Service section
	[params.services]
		headline = "Services tailored to your child."

        [[params.services.list]]
            icon = "fa-university"
            title = "After-school Tuition"
            description = "I offer after-school and weekend tuition."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Dyslexia"
			description = "Specialised Dyslexia teaching"

		[[params.services.list]]
            icon = "fa-book"
            title = "Dyspraxia"
            description = "Specialised Dyspraxia teaching"

        [[params.services.list]]
            icon = "fa-graduation-cap"
            title = "Aspergers syndrome"
            description = "Individual plans tailed for Aspergers syndrome"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	##[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact details"
		description = "Faliure to give each individual a chance to shine and fulfil thier true potential is one of the greatest tragedies of our time"
		phone = "01935 872365"
		phoneMobile = "07814 712662"
		email = "daphneblakey@gmail.com"

	# Google Maps section
	 [params.location]

	 	latitude  = "50.8955465"
	 	longitude = "-2.5980245"
	# 	maps_api_key = ""

	#Footer
	[params.footer]
		footerText = "This website uses cookies. By continuing to browse this site you are agreeing to our use of cookies.Free hosting provided by GitHub Pages"


